name: Box接口

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: tools
        run: |
          pwd 
          cd tools/
          pip install demjson3 requests==2.31.0
          python ok.py
          python jo.py
          python combine.py
          # \cp -pdr dianshi_merged_with_app_sites.json ../dianshi.json
          # \cp -pdr jsm_merged_with_app_sites.json ../jsm.json
          # \cp -pdr fan.txt ../jar/fan.txt
          # rm -rf dianshi_merged_with_app_sites.json jsm_merged_with_app_sites.json dianshi_merged.json jsm_merged.json tvbox_cleaned.json fan.txt
          # cd ../
        shell: bash
        
      - name: 提交更改
        run: | 
          git config user.email "zhoujck@live.com"
          git config user.name "zhoujck" 
          git add .
          if ! git diff-index --quiet HEAD --; then
          git commit -m "更新源 $(date +%Y%m%d%H%M)"
          git push -f origin main
          else
          echo "没有文件更新，不执行 git push"
          fi
     
