name: OK接口

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install demjson3 requests==2.31.0

      - name: Run tools
        run: |
        cd tools/
        python ok.py
        python jo.py
        python combine.py     
        
      - name: 提交更改
        run: |
          git config user.email "zhoujck@live.com"
          git config user.name "zhoujck" 
          git add .
          if ! git diff-index --quiet HEAD --; then
          git commit -m "更新源 $(date +%Y%m%d%H%M)"
          git push -f origin main
          else
          echo "没有文件更新，不执行 git push"
          fi
     
